server:
  port: 3003

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      # 注册到 eureka
      defaultZone: http://localhost:1110/eureka
spring:
  application:
    # 应用程序名称，后面会在消费者中用到
    name: config-server