server:
  port: 3009

spring:
#  kafka:
#    consumer:
#      enable-auto-commit: true
#      group-id: app-group-1
#      auto-offset-reset: latest
#      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
            - localhost:9093
            - localhost:9094
        bindings:
          test-topic:
            consumer:
              topic:
                replicas-assignment:
                replication-factor: 2

            binder: kafka
            destination: test-topic #topic name
            content-type: text/plain
            group: input-group-1