server:
  port: 80

spring:
  application:
    # 应用程序名称，后面会在消费者中用到
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启通过服务中心的自动根据serviceId创建路由的功能
          lower-case-service-id: true #使用小写service-id
#      routes:
#      - id: demo_route
#        uri: lb://api-demo
#        predicates:
#        - Path=/api-demo/**
#        filters:
#        - StripPrefix=2
#        - name: ApiAuth
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/fallback
#      - id: customer_route
#        uri: lb://api-customer
#        predicates:
#        - Path=/api-customer/**
#        filters:
#        - StripPrefix=1
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/fallback

# 开启熔断器功能
feign:
  hystrix:
    enabled: true

# Hystrix 配置
hystrix:
  command:
    default:
      # circuitBreaker:
        # 强制将断路器设置成开启状态
        # forceOpen: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # Hystrix fallbackcmd 的熔断时间
  threadpool:
    default:
      coreSize: 100 # Hystrix 更改默认并发数配置

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      # 注册到 eureka
      defaultZone: http://localhost:1110/eureka

ribbon:
  eureka:
    enabled: true

api-demo:
  ribbon:
    ServerListRefreshInterval: 60000
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerPingClassName: com.lc.learning.swarm.gateway.loadbanlance.HealthExamination