server:
  port: 1111
eureka:
  instance:
    hostname: eureka-peer1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-peer2:1112/eureka/,http://eureka-peer3:1113/eureka/
  server:
    enable-self-preservation: false