server:
  port: 1112
eureka:
  instance:
    hostname: eureka-peer2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-peer1:1111/eureka/,http://eureka-peer3:1113/eureka/
  server:
    enable-self-preservation: false