server:
  port: 1111
eureka:
  instance:
    hostname: master
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://backup1:1112/eureka/,http://backup2:1113/eureka/
  server:
    enable-self-preservation: false