server:
  port: 1113
eureka:
  instance:
    hostname: eureka-peer3
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-peer1:1111/eureka/,http://eureka-peer2:1112/eureka/
  server:
    enable-self-preservation: false