server:
  port: 1112
eureka:
  instance:
    hostname: backup1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://master:1111/eureka/,http://backup2:1113/eureka/
  server:
    enable-self-preservation: false