server:
  port: 1110
eureka:
  instance:
    hostname: eureka-center
    appname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false # 单点的时候设置为 false 禁止注册自身
    service-url:
      default-zone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false
    evictionIntervalTimerInMs: 4000