server:
  port: 1113
eureka:
  instance:
    hostname: backup2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://master:1111/eureka/,http://backup1:1112/eureka/
  server:
    enable-self-preservation: false