server:
  port: 80

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      # 注册到 eureka
      defaultZone: http://localhost:1110/eureka
      # defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/

spring:
  application:
    # 应用程序名称，后面会在消费者中用到
    name: gateway
  cloud:
    gateway:
      # cors跨域反问配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false #开启通过服务中心的自动根据serviceId创建路由的功能(这里不能用true，true会自动生成路由，复盖配置的路由)
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: config_route
          uri: lb://config-server
          predicates:
            - Path=/config-server/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: refreshconfig
                fallbackUri: forward:/fallback
        - id: producer_route
          uri: lb://api-producer
          predicates:
            - Path=/api-producer/**
          filters:
            - StripPrefix=1
            - name: ApiAuth
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
        - id: customer_refresh_config
          uri: lb://api-customer
          predicates:
            - Path=/api-customer/actuator/refresh
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: refreshconfig
                fallbackUri: forward:/fallback
        - id: customer_route
          uri: lb://api-customer
          predicates:
            - Path=/api-customer/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

# 开启熔断器功能
feign:
  hystrix:
    enabled: true

# Hystrix 配置
hystrix:
  command:
    default:
      # circuitBreaker:
      # 强制将断路器设置成开启状态
      # forceOpen: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # Hystrix fallbackcmd 的熔断时间
    refreshconfig:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  threadpool:
    default:
      coreSize: 100 # Hystrix 更改默认并发数配置

ribbon:
  eureka:
    enabled: true

api-producer:
  ribbon:
    ServerListRefreshInterval: 5000
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    # 均衡负载，本策略是轮询节点
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerPingClassName: HealthExamination

api-customer:
  ribbon:
    ServerListRefreshInterval: 5000
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    # 均衡负载，本策略是轮询节点
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerPingClassName: HealthExamination