spring:
  application:
    name: logback-starter

#日志信息的配置
logback:
  # true 表示打印日志  false表示不打印日志
  logSwitch: true
  logDir: /data/logs/log-starter
  debugName: debug
  infoName: info
  errorName: error
  warnName: warn
  logIp: ${spring.cloud.client.ip-address}
logging:
  config: classpath:logback-config.xml